version: "2"
services:
  web:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - ./:/quartfeed_app
    links:
      - db:mysql
    container_name: quartfeed_web_1
    depends_on:
      - db
    stdin_open: true
    tty: true
    environment:
      PORT: 5000
      SECRET_KEY: "you-will-never-guess"
      DEBUG: 1
      MYSQL_ROOT_PASSWORD: rootpass
      DB_USERNAME: qf_user
      DB_PASSWORD: qf_password
      DB_HOST: mysql
      DATABASE_NAME: quartfeed
      UPLOAD_FOLDER: "/quartfeed_app/static/uploads"
      IMAGES_FOLDER: "/quartfeed_app/static/images"
      IMAGES_URL: "http://localhost:5000/static/images"
  db:
    image: mysql:5.7
    restart: always
    container_name: quartfeed_db_1
    ports:
      - "3306:3306"
    environment:
      MYSQL_USER: qf_user
      MYSQL_PASSWORD: qf_password
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: quartfeed
